"""initial schema

Revision ID: 0126b2d5742a
Revises: 
Create Date: 2026-06-28 10:36:14.681763
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from tt_ledger.money import Money

# revision identifiers, used by Alembic.
revision: str = '0126b2d5742a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('account_number', sa.String(length=32), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('env', sa.String(length=8), nullable=False),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_login'), ['login'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_nickname'), ['nickname'], unique=True)

    op.create_table('securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.String(length=64), nullable=False),
    sa.Column('product_type', sa.String(length=2), nullable=False),
    sa.Column('underlying', sa.String(length=32), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('strike', Money(scale=6), nullable=True),
    sa.Column('option_type', sa.String(length=1), nullable=True),
    sa.Column('multiplier', sa.Integer(), nullable=True),
    sa.Column('exchange', sa.String(length=16), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('tt_symbol', sa.String(length=100), nullable=True),
    sa.Column('occ_symbol', sa.String(length=32), nullable=True),
    sa.Column('streamer_symbol', sa.String(length=50), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_securities_security_id'), ['security_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_securities_streamer_symbol'), ['streamer_symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_securities_tt_symbol'), ['tt_symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_securities_underlying'), ['underlying'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tt_order_id', sa.String(length=64), nullable=True),
    sa.Column('oms_order_id', sa.String(length=64), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=True),
    sa.Column('account', sa.String(length=50), nullable=False),
    sa.Column('account_number', sa.String(length=32), nullable=True),
    sa.Column('origin', sa.String(length=8), nullable=False),
    sa.Column('ingest', sa.String(length=16), nullable=False),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('security_id', sa.String(length=64), nullable=True),
    sa.Column('underlying', sa.String(length=32), nullable=True),
    sa.Column('order_type', sa.String(length=24), nullable=True),
    sa.Column('time_in_force', sa.String(length=16), nullable=True),
    sa.Column('gtc_date', sa.String(length=10), nullable=True),
    sa.Column('price', Money(scale=6), nullable=True),
    sa.Column('stop_trigger', Money(scale=6), nullable=True),
    sa.Column('price_effect', sa.String(length=8), nullable=True),
    sa.Column('average_fill_price', Money(scale=6), nullable=True),
    sa.Column('is_complex', sa.Boolean(), nullable=False),
    sa.Column('complex_order_type', sa.String(length=16), nullable=True),
    sa.Column('oms_status', sa.String(length=24), nullable=True),
    sa.Column('tt_status', sa.String(length=24), nullable=True),
    sa.Column('status_message', sa.String(length=256), nullable=True),
    sa.Column('filled_quantity', Money(scale=6), nullable=True),
    sa.Column('remaining_quantity', Money(scale=6), nullable=True),
    sa.Column('signal_id', sa.String(length=128), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('trade_group_id', sa.Integer(), nullable=True),
    sa.Column('market_context_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account'], ['accounts.nickname'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.security_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_account'), ['account'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_oms_order_id'), ['oms_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_signal_id'), ['signal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_trade_group_id'), ['trade_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_underlying'), ['underlying'], unique=False)
        batch_op.create_index('uq_orders_tt_order_id', ['tt_order_id'], unique=True, sqlite_where=sa.text('tt_order_id IS NOT NULL'), postgresql_where=sa.text('tt_order_id IS NOT NULL'))

    op.create_table('order_legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('leg_index', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('quantity', Money(scale=6), nullable=True),
    sa.Column('remaining_quantity', Money(scale=6), nullable=True),
    sa.Column('quantity_direction', sa.String(length=8), nullable=True),
    sa.Column('price', Money(scale=6), nullable=True),
    sa.Column('fill_price', Money(scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.security_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_legs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_legs_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_legs_security_id'), ['security_id'], unique=False)

    op.create_table('trade_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('account', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=8), nullable=False),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('manually_attributed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('underlying', sa.String(length=32), nullable=True),
    sa.Column('security_id', sa.String(length=64), nullable=True),
    sa.Column('strategy_type', sa.String(length=24), nullable=True),
    sa.Column('leg_count', sa.Integer(), nullable=False),
    sa.Column('total_premium', Money(scale=6), nullable=True),
    sa.Column('quantity', Money(scale=6), nullable=True),
    sa.Column('total_fees', Money(scale=6), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('realized_pnl', Money(scale=6), nullable=True),
    sa.Column('unrealized_pnl', Money(scale=6), nullable=True),
    sa.Column('max_profit', Money(scale=6), nullable=True),
    sa.Column('max_loss', Money(scale=6), nullable=True),
    sa.Column('profit_target', sa.String(length=32), nullable=True),
    sa.Column('stop_loss', sa.String(length=32), nullable=True),
    sa.Column('exit_strategy', sa.String(length=100), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('bot_name', sa.String(length=64), nullable=True),
    sa.Column('signal_id', sa.String(length=128), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account'], ['accounts.nickname'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_groups_account'), ['account'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_groups_bot_name'), ['bot_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_groups_group_id'), ['group_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_trade_groups_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_groups_review_status'), ['review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_groups_signal_id'), ['signal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_groups_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_groups_underlying'), ['underlying'], unique=False)

    op.create_table('closed_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=50), nullable=False),
    sa.Column('security_id', sa.String(length=64), nullable=False),
    sa.Column('quantity', Money(scale=6), nullable=False),
    sa.Column('quantity_direction', sa.String(length=8), nullable=False),
    sa.Column('average_open_price', Money(scale=6), nullable=True),
    sa.Column('average_close_price', Money(scale=6), nullable=True),
    sa.Column('realized_pnl', Money(scale=6), nullable=True),
    sa.Column('opening_order_id', sa.Integer(), nullable=True),
    sa.Column('closing_order_id', sa.Integer(), nullable=True),
    sa.Column('trade_group_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('holding_period_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account'], ['accounts.nickname'], ),
    sa.ForeignKeyConstraint(['closing_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['opening_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.security_id'], ),
    sa.ForeignKeyConstraint(['trade_group_id'], ['trade_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('closed_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_closed_positions_account'), ['account'], unique=False)
        batch_op.create_index(batch_op.f('ix_closed_positions_security_id'), ['security_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_closed_positions_trade_group_id'), ['trade_group_id'], unique=False)

    op.create_table('order_fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_leg_id', sa.Integer(), nullable=True),
    sa.Column('tt_order_id', sa.String(length=64), nullable=True),
    sa.Column('fill_id', sa.String(length=64), nullable=False),
    sa.Column('quantity', Money(scale=6), nullable=True),
    sa.Column('fill_price', Money(scale=6), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('destination_venue', sa.String(length=32), nullable=True),
    sa.Column('ext_exec_id', sa.String(length=64), nullable=True),
    sa.Column('ext_group_fill_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_leg_id'], ['order_legs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fill_id')
    )
    with op.batch_alter_table('order_fills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_fills_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_fills_order_leg_id'), ['order_leg_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_fills_tt_order_id'), ['tt_order_id'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=50), nullable=False),
    sa.Column('security_id', sa.String(length=64), nullable=False),
    sa.Column('quantity', Money(scale=6), nullable=False),
    sa.Column('quantity_direction', sa.String(length=8), nullable=False),
    sa.Column('average_open_price', Money(scale=6), nullable=True),
    sa.Column('mark_price', Money(scale=6), nullable=True),
    sa.Column('close_price', Money(scale=6), nullable=True),
    sa.Column('unrealized_pnl', Money(scale=6), nullable=True),
    sa.Column('realized_day_gain', Money(scale=6), nullable=True),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('opening_order_id', sa.Integer(), nullable=True),
    sa.Column('trade_group_id', sa.Integer(), nullable=True),
    sa.Column('position_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account'], ['accounts.nickname'], ),
    sa.ForeignKeyConstraint(['opening_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.security_id'], ),
    sa.ForeignKeyConstraint(['trade_group_id'], ['trade_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_account'), ['account'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_opening_order_id'), ['opening_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_security_id'), ['security_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_trade_group_id'), ['trade_group_id'], unique=False)
        batch_op.create_index('uq_positions_account_security', ['account', 'security_id'], unique=True)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tt_transaction_id', sa.String(length=64), nullable=False),
    sa.Column('tt_order_id', sa.String(length=64), nullable=True),
    sa.Column('account', sa.String(length=50), nullable=False),
    sa.Column('account_number', sa.String(length=32), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('transaction_sub_type', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=True),
    sa.Column('security_id', sa.String(length=64), nullable=True),
    sa.Column('underlying', sa.String(length=32), nullable=True),
    sa.Column('quantity', Money(scale=6), nullable=True),
    sa.Column('price', Money(scale=6), nullable=True),
    sa.Column('value', Money(scale=6), nullable=True),
    sa.Column('value_effect', sa.String(length=10), nullable=True),
    sa.Column('net_value', Money(scale=6), nullable=True),
    sa.Column('net_value_effect', sa.String(length=10), nullable=True),
    sa.Column('commission', Money(scale=6), nullable=True),
    sa.Column('clearing_fees', Money(scale=6), nullable=True),
    sa.Column('regulatory_fees', Money(scale=6), nullable=True),
    sa.Column('proprietary_index_option_fees', Money(scale=6), nullable=True),
    sa.Column('is_estimated_fee', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('order_leg_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('closed_position_id', sa.Integer(), nullable=True),
    sa.Column('trade_group_id', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account'], ['accounts.nickname'], ),
    sa.ForeignKeyConstraint(['closed_position_id'], ['closed_positions.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_leg_id'], ['order_legs.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.security_id'], ),
    sa.ForeignKeyConstraint(['trade_group_id'], ['trade_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_account'), ['account'], unique=False)
        batch_op.create_index('ix_transactions_account_date', ['account', 'transaction_date'], unique=False)
        batch_op.create_index('ix_transactions_account_executed', ['account', 'executed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_closed_position_id'), ['closed_position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_order_leg_id'), ['order_leg_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_position_id'), ['position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_trade_group_id'), ['trade_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_tt_order_id'), ['tt_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_tt_transaction_id'), ['tt_transaction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_underlying'), ['underlying'], unique=False)

    op.create_table('trade_group_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_group_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('quantity_change', Money(scale=6), nullable=False),
    sa.Column('premium_change', Money(scale=6), nullable=False),
    sa.Column('realized_pnl', Money(scale=6), nullable=True),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rolled_to_group_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['rolled_to_group_id'], ['trade_groups.id'], ),
    sa.ForeignKeyConstraint(['trade_group_id'], ['trade_groups.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_group_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_group_events_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_group_events_rolled_to_group_id'), ['rolled_to_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_group_events_trade_group_id'), ['trade_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_group_events_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_group_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_group_events_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_trade_group_events_trade_group_id'))
        batch_op.drop_index(batch_op.f('ix_trade_group_events_rolled_to_group_id'))
        batch_op.drop_index(batch_op.f('ix_trade_group_events_order_id'))

    op.drop_table('trade_group_events')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_underlying'))
        batch_op.drop_index(batch_op.f('ix_transactions_tt_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_tt_order_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_trade_group_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_position_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_order_leg_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_order_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_closed_position_id'))
        batch_op.drop_index('ix_transactions_account_executed')
        batch_op.drop_index('ix_transactions_account_date')
        batch_op.drop_index(batch_op.f('ix_transactions_account'))

    op.drop_table('transactions')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index('uq_positions_account_security')
        batch_op.drop_index(batch_op.f('ix_positions_trade_group_id'))
        batch_op.drop_index(batch_op.f('ix_positions_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_positions_security_id'))
        batch_op.drop_index(batch_op.f('ix_positions_opening_order_id'))
        batch_op.drop_index(batch_op.f('ix_positions_account'))

    op.drop_table('positions')
    with op.batch_alter_table('order_fills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_fills_tt_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_fills_order_leg_id'))
        batch_op.drop_index(batch_op.f('ix_order_fills_order_id'))

    op.drop_table('order_fills')
    with op.batch_alter_table('closed_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_closed_positions_trade_group_id'))
        batch_op.drop_index(batch_op.f('ix_closed_positions_security_id'))
        batch_op.drop_index(batch_op.f('ix_closed_positions_account'))

    op.drop_table('closed_positions')
    with op.batch_alter_table('trade_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_groups_underlying'))
        batch_op.drop_index(batch_op.f('ix_trade_groups_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_trade_groups_signal_id'))
        batch_op.drop_index(batch_op.f('ix_trade_groups_review_status'))
        batch_op.drop_index(batch_op.f('ix_trade_groups_order_id'))
        batch_op.drop_index(batch_op.f('ix_trade_groups_group_id'))
        batch_op.drop_index(batch_op.f('ix_trade_groups_bot_name'))
        batch_op.drop_index(batch_op.f('ix_trade_groups_account'))

    op.drop_table('trade_groups')
    with op.batch_alter_table('order_legs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_legs_security_id'))
        batch_op.drop_index(batch_op.f('ix_order_legs_order_id'))

    op.drop_table('order_legs')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('uq_orders_tt_order_id', sqlite_where=sa.text('tt_order_id IS NOT NULL'), postgresql_where=sa.text('tt_order_id IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_orders_underlying'))
        batch_op.drop_index(batch_op.f('ix_orders_trade_group_id'))
        batch_op.drop_index(batch_op.f('ix_orders_trace_id'))
        batch_op.drop_index(batch_op.f('ix_orders_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_orders_signal_id'))
        batch_op.drop_index(batch_op.f('ix_orders_oms_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_account'))

    op.drop_table('orders')
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_securities_underlying'))
        batch_op.drop_index(batch_op.f('ix_securities_tt_symbol'))
        batch_op.drop_index(batch_op.f('ix_securities_streamer_symbol'))
        batch_op.drop_index(batch_op.f('ix_securities_security_id'))

    op.drop_table('securities')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_nickname'))
        batch_op.drop_index(batch_op.f('ix_accounts_login'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
